version: '3.4'

services:
  issuetrackerspacex:
    image: issuetrackerspacex:v0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
